# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0006_auto_20170306_1913'),
        ('doctors', '0003_auto_20170306_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(max_length=255, verbose_name=b'2')),
                ('tuesday', models.BooleanField(max_length=255, verbose_name=b'3')),
                ('wednesday', models.BooleanField(max_length=255, verbose_name=b'4')),
                ('thursday', models.BooleanField(max_length=255, verbose_name=b'5')),
                ('friday', models.BooleanField(max_length=255, verbose_name=b'6')),
                ('doctors', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor', verbose_name=b'M\xc3\xa9dico')),
                ('terapy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name=b'Categoria')),
            ],
            options={
                'ordering': ['doctors'],
                'verbose_name': 'Atendimento',
            },
        ),
    ]
