# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Nome da Crian\xc3\xa7a')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name=b'Data de Nascimento')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Crianca',
                'verbose_name_plural': 'Criancas',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Nome')),
                ('dni', models.EmailField(max_length=255, unique=True, verbose_name=b'DNI')),
                ('primary_contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name=b'Contato principal')),
                ('cellphone', models.CharField(blank=True, max_length=15, null=True, verbose_name=b'Celular')),
                ('email', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'email')),
                ('address', models.CharField(blank=True, max_length=15, null=True, verbose_name=b'Celular')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Responsavel',
                'verbose_name_plural': 'Responsaveis',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.Person', verbose_name=b'Respons\xc3\xa1vel'),
        ),
    ]
