# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('categories', '0002_auto_20170306_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='doctor', to='doctors.Doctor', verbose_name=b'M\xc3\xa9dicos'),
        ),
    ]
