# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='doctors',
        ),
    ]
