# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20170306_1830'),
        ('categories', '0004_remove_category_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctors.Doctor', verbose_name=b'M\xc3\xa9dicos'),
        ),
    ]
