# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20170306_1830'),
        ('categories', '0005_category_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='doctors',
        ),
        migrations.AddField(
            model_name='category',
            name='doctors',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctors', to='doctors.Doctor', verbose_name=b'M\xc3\xa9dicos'),
        ),
    ]
