# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_terapy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='end_time',
            new_name='hours',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='weekday',
            field=models.CharField(default='', max_length=255, verbose_name=b'Dias de atendimento'),
            preserve_default=False,
        ),
    ]
