# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20170306_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hours',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Horario de atendimento'),
        ),
    ]
