# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20170306_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='weekday',
            field=models.CharField(choices=[(b'seg', b'segunda'), (b'ter', b'terca')], max_length=255, verbose_name=b'Dias de atendimento'),
        ),
    ]
