# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapies', '0001_initial'),
        ('patients', '0006_auto_20170306_1908'),
        ('appointments', '0007_auto_20170307_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['therapie'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctors',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='weekday',
        ),
        migrations.AddField(
            model_name='appointment',
            name='child',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='patients.Child', verbose_name=b'Paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='therapie',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='therapies.Therapie', verbose_name=b'Terapia'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Weekdays',
        ),
    ]
