# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'nome da crian\xc3\xa7a')),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name=b'Data de Nascimento')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Crianca',
                'verbose_name_plural': 'Criancas',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Nome')),
                ('dni', models.EmailField(max_length=255, unique=True, verbose_name=b'DNI')),
                ('primary_contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name=b'Contato principal')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, verbose_name=b'Telefone')),
                ('cellphone', models.CharField(blank=True, max_length=15, null=True, verbose_name=b'Celular')),
                ('email', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'email')),
                ('address', models.CharField(blank=True, max_length=15, null=True, verbose_name=b'endere\xc3\xa7o')),
                ('city', models.CharField(max_length=100, verbose_name=((b'Mendoza', b'Mendoza'), (b'General Alvear', b'General Alvear'), (b'General San Mart\xc3\xadn', b'General San Mart\xc3\xadn'), (b'Godoy Cruz', b'Godoy Cruz'), (b'Guaymall\xc3\xa9n', b'Guaymall\xc3\xa9n'), (b'Jun\xc3\xadn', b'Jun\xc3\xadn'), (b'La Paz', b'La Paz'), (b'Las Heras', b'Las Heras'), (b'Lavalle', b'Lavalle'), (b'Luj\xc3\xa1n de Cuyo ', b'Luj\xc3\xa1n de Cuyo '), (b'Maip\xc3\xba ', b'Maip\xc3\xba '), (b'Malarg\xc3\xbce', b'Malarg\xc3\xbce'), (b'Rivadavia', b'Rivadavia'), (b'San Carlos ', b'San Carlos'), (b'San Rafael ', b'San Rafael'), (b'Santa Rosa ', b'Santa Rosa'), (b'Tunuy\xc3\xa1n', b'Tunuy\xc3\xa1n'), (b'Tupungato ', b'Tupungato'), (b'outros', b'Outros')))),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Responsavel',
                'verbose_name_plural': 'Responsaveis',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='patients.Person', verbose_name=b'Respons\xc3\xa1vel'),
        ),
    ]
