# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_category_doctors'),
        ('doctors', '0003_auto_20170306_1830'),
        ('patients', '0004_auto_20170306_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name=b'categoria do m\xc3\xa9dico')),
                ('name', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor', verbose_name=b'nome do m\xc3\xa9dico')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='patients.DoctorChild', verbose_name=b'M\xc3\xa9dico'),
        ),
    ]
