# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20170306_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='doctor',
        ),
        migrations.AddField(
            model_name='child',
            name='doctors',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctors', to='patients.DoctorChild', verbose_name=b'M\xc3\xa9dico'),
        ),
    ]
