# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20170306_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='categories.Category', verbose_name=b'Categoria'),
        ),
    ]
